# Generated by Django 2.0.2 on 2018-03-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(max_length=20)),
                ('sub_type', models.CharField(max_length=20)),
                ('reply_text', models.CharField(max_length=200)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_order', models.IntegerField(default=0)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner16.Communication')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner16.Reply')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(max_length=20)),
                ('sub_type', models.CharField(max_length=20)),
                ('statement_text', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement_Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_order', models.IntegerField(default=0)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner16.Communication')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner16.Statement')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='reply',
            field=models.ManyToManyField(through='partner16.Reply_Set', to='partner16.Reply'),
        ),
        migrations.AddField(
            model_name='communication',
            name='statement',
            field=models.ManyToManyField(through='partner16.Statement_Flow', to='partner16.Statement'),
        ),
    ]
